# MySQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bootex?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: bootuser
    password: bootuser
    driver-class-name: com.mysql.cj.jdbc.Driver
